name: mimic-multimodal
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas>=2.1
  - numpy
  - matplotlib
  - seaborn
  - tqdm
  - jupyter
  - pip
  - pip:
      - pyarrow
      - matplotlib-venn
